"""init models

Revision ID: b296f4afaa53
Revises:
Create Date: 2026-05-04 23:36:38.714011

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b296f4afaa53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('status', sa.String(), nullable=True))
    op.create_index(
        op.f('ix_pedido_id_estabelecimento'),
        'pedido',
        ['id_estabelecimento'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_id_estabelecimento'), table_name='pedido')
    op.drop_column('pedido', 'status')
    # ### end Alembic commands ###
